# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  before_build:
    - ps: nuget restore .\Confluent.Kafka.Utility.sln
  build:
    project: .\Confluent.Kafka.Utility.sln
# configuration for all other branches except "master"
-
  branches:
    except:
      - master
  configuration: Test
  before_build:
    - ps: nuget restore .\Confluent.Kafka.Utility.sln
  build:
    project: .\Confluent.Kafka.Utility.sln
